service: slack-foodbot

# Only deploy with a specific Serverless version
frameworkVersion: "=1.9.0"

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: eu-west-1
  versionFunctions: false

package:
  include:
    - handler.js
  exclude:
    - ./**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
