service: slack-foodbot2

frameworkVersion: "~1.25"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

functions:
  sendFoodletter:
    handler: foodletter/handlers.sendFoodletter
    events:
      - schedule: cron(0 11 ? * MON-FRI *) # 12:00 CET during workdays
