service: slack-foodbot2

frameworkVersion: "~1.25"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  sendFoodletter:
    handler: foodletter/handlers.sendFoodletter

    events:
      - http:
          path: sendFoodletter
          method: get
#      - schedule: rate(10 minutes)
