service: slack-foodbot

# Only deploy with a specific Serverless version
frameworkVersion: "=1.9.0"

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: eu-west-1
  versionFunctions: false

package:
  include:
    - dist/**
    - node_modules/**
    - settings.json
  exclude:
    - ./**

functions:
  slash:
    handler: dist/main.slash
    events:
      - http:
          path: slash
          method: get
      - http:
          path: slash
          method: post
